services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DATABASE_URL=jdbc:postgresql://database:5432/mensa
      - LLM_SERVICE_URL=http://llm:5000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    ports:
      - "8080:8080"
    restart: unless-stopped

  database:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-supersecret}
      - POSTGRES_DB=${POSTGRES_DB:-mensa}
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PUBLIC_API_URL=${PUBLIC_API_URL:-http://localhost:8080/api}
    depends_on:
      - server
    restart: unless-stopped

  llm:
    build:
      context: ./llm
      dockerfile: Dockerfile
    environment:
      - CHAIR_API_KEY=${CHAIR_API_KEY:-your_api_key_here}
    ports:
      - "5001:5000"
    restart: unless-stopped

volumes:
  db_data: