# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: meal_recommendation.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'meal_recommendation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19meal_recommendation.proto\x12\ttum.mensa\"m\n\x19MealRecommendationRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x16\n\x0e\x66\x61vorite_meals\x18\x02 \x03(\t\x12\'\n\ntoday_menu\x18\x03 \x03(\x0b\x32\x13.tum.mensa.MenuMeal\";\n\x08MenuMeal\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x0c\n\x04tags\x18\x03 \x03(\t\"N\n\x1aMealRecommendationResponse\x12\x1d\n\x15recommended_meal_name\x18\x01 \x01(\t\x12\x11\n\treasoning\x18\x02 \x01(\t2y\n\x19MealRecommendationService\x12\\\n\rRecommendMeal\x12$.tum.mensa.MealRecommendationRequest\x1a%.tum.mensa.MealRecommendationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'meal_recommendation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MEALRECOMMENDATIONREQUEST']._serialized_start=40
  _globals['_MEALRECOMMENDATIONREQUEST']._serialized_end=149
  _globals['_MENUMEAL']._serialized_start=151
  _globals['_MENUMEAL']._serialized_end=210
  _globals['_MEALRECOMMENDATIONRESPONSE']._serialized_start=212
  _globals['_MEALRECOMMENDATIONRESPONSE']._serialized_end=290
  _globals['_MEALRECOMMENDATIONSERVICE']._serialized_start=292
  _globals['_MEALRECOMMENDATIONSERVICE']._serialized_end=413
# @@protoc_insertion_point(module_scope)
