# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import meal_recommendation_pb2 as meal__recommendation__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in meal_recommendation_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MealRecommendationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RecommendMeal = channel.unary_unary(
                '/tum.mensa.MealRecommendationService/RecommendMeal',
                request_serializer=meal__recommendation__pb2.MealRecommendationRequest.SerializeToString,
                response_deserializer=meal__recommendation__pb2.MealRecommendationResponse.FromString,
                _registered_method=True)


class MealRecommendationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RecommendMeal(self, request, context):
        """Recommend a meal for the user based on today's menu and previous favorites
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MealRecommendationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RecommendMeal': grpc.unary_unary_rpc_method_handler(
                    servicer.RecommendMeal,
                    request_deserializer=meal__recommendation__pb2.MealRecommendationRequest.FromString,
                    response_serializer=meal__recommendation__pb2.MealRecommendationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tum.mensa.MealRecommendationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tum.mensa.MealRecommendationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MealRecommendationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RecommendMeal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tum.mensa.MealRecommendationService/RecommendMeal',
            meal__recommendation__pb2.MealRecommendationRequest.SerializeToString,
            meal__recommendation__pb2.MealRecommendationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
